
name: auto run
on:
  schedule:
    # cron 格式：分 时 * * *，UTC时间 = 北京时间 - 8小时
    # 北京时间21:21 → UTC 13:21
    - cron: '21 13 * * *'
  workflow_dispatch: #支持手动点按钮测试

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 运行签到脚本
        env:
          STUDENT_ID: ${{ secrets.STUDENT_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main_sync.py
