name: Python Async ahut_wqqd

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '21 13 * * *' # UTC 13:21 = 北京时间 21:21

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run main.py
        run: python main.py
